// Vue/VueDemo/vue_test/34_src_路由_parmas参数/pages/Message.vue
<template>
  <div>
    <ul>
      <li v-for="m in messageList" :key="m.id">
        <!--跳转路由并携带params参数，to的字符串写法-->
<!--        <router-link :to="`/home/message/detail/${m.id}/${m.title}`">{{m.title}}</router-link>&nbsp;&nbsp;-->
        <!--跳转路由并携带params参数，to的对象写法-->
        <router-link :to="{
        //  用parmas传参这里必须用name，不能用path
        name:'xiangqing',
        params:{
          id:m.id,
          title:m.title
        }
        }">
          {{m.title}}
        </router-link>&nbsp;
      </li>
    </ul>
    <hr/>
    <router-view></router-view>
  </div>
</template>

<script>
export default {
  name: "Message",
  data() {
    return{
      messageList:[
        {id:'0001',title:'消息0001'},
        {id:'0002',title:'消息0002'},
        {id:'0003',title:'消息0003'},
        {id:'0004',title:'消息0004'},
      ]
    }
  }
};
</script>

<style scoped>

</style>

// React/shang_react/staging/17_向路由组件传递search参数/pages/Home/Message/index.jsx
import React, { Component } from "react";
import { Link, Route } from "react-router-dom";
import Detail from "./Detail";
export default class Message extends Component {
  state = {
    messageArr: [
      { id: "001", title: "消息1" },
      { id: "002", title: "消息2" },
      { id: "003", title: "消息3" },
      { id: "004", title: "消息4" },
    ],
  };
  render() {
    const { messageArr } = this.state;
    return (
      <div>
        <ul>
          {messageArr.map((msgObj) => {
            return (
              <li key={msgObj.id}>
                {/* 向路由组件传递params参数 */}
                {/* <Link to={`/home/message/detail/${msgObj.id}/${msgObj.title}`}>
                  {msgObj.title}
                </Link> */}

                {/* 向路由组件传递search参数 */}
                <Link
                  to={`/home/message/detail/?id=${msgObj.id}&title=${msgObj.title}`}
                >
                  {msgObj.title}
                </Link>
              </li>
            );
          })}
        </ul>
        <hr />
        {/* 声明接受parmas参数 */}
        {/* <Route path="/home/message/detail/:id/:title" component={Detail} /> */}

        {/* search参数无需声明接受，正常注册路由即可 */}
        <Route path="/home/message/detail" component={Detail} />

      </div>
    );
  }
}
