// Vue/VueDemo/vue_test/19_src_配置代理服务器/App.vue
<template>
  <div id="root">
    <button @click="getStudents">获取学生信息</button>
    <button @click="getCars">获取汽车数据</button>
  </div>
</template>

<script>
import axios from "axios";
export default {
  name: "App",
  methods: {
    getStudents() {
      axios.get("http://localhost:8080/atguigu/students").then(
        (response) => {
          console.log("请求成功了", response.data);
        },
        (error) => {
          console.log("请求失败", error.message);
        }
      );
    },
    getCars() {
      axios.get("http://localhost:8080/moer/cars").then(
        (response) => {
          console.log("请求成功了", response.data);
        },
        (error) => {
          console.log("请求失败", error.message);
        }
      );
    },
  },
};
</script>

// React/shang_react/staging/04_axios配置/App.jsx
import React, { Component } from "react";
import axios from "axios";
export default class App extends Component {
  getStudentData = () => {
    axios.get("http://localhost:3000/api1/students").then(
      (response) => {
        console.log('成功了',response.data);
      },
      (error) => {
        console.log('失败了',error);
      }
    );
  };
  getCarData = () => {
    axios.get("http://localhost:3000/api2/cars").then(
      (response) => {
        console.log('成功了',response.data);
      },
      (error) => {
        console.log('失败了',error);
      }
    );
  };
  render() {
    return (
      <div>
        App...
        <button onClick={this.getStudentData}>点我获取学生数据</button>
        <button onClick={this.getCarData}>点我获取汽车数据</button>

      </div>
    );
  }
}
