// React/shang_react/redux_test/7_react-redux_数据共享版/App.jsx
import React, { Component } from "react";
import Count from "./containers/Count";
import Person from "./containers/Person";
export default class App extends Component {
  render() {
    return (
      <div>
        {/* 给容器组件传递store */}
        {/* <Count store={store}/> */}
        <Count />
        <hr />
        <Person />
      </div>
    );
  }
}

// Vue/VueDemo/vue_test/29_src_求和案例_模块化和命名空间/App.vue
<template>
  <div>
    <Count />
    <hr />
    <Person />
  </div>
</template>

<script>
import Person from "./components/Person.vue";
import Count from "./components/Count.vue";
export default {
  name: "App",
  components: {
    Count,
    Person,
  },
  mounted() {
    // console.log("App", this);
  },
};
</script>
