// Vue/VueDemo/vue_test/28_src_求和案例_多组件共享数据/components/Person.vue
<template>
  <div>
    <h1>人员列表</h1>
    <h2 style="color:red">上方Count组件的求和为：{{ sum }}</h2>
    <input type="text" placeholder="请输入名字" v-model="name" />
    <button @click="add">添加</button>
    <ul>
      <li v-for="p in personList" :key="p.id">{{ p.name }}</li>
    </ul>
  </div>
</template>

<script>
import { nanoid } from "nanoid";
// import { mapState } from "vuex";
export default {
  name: "Person",
  computed: {
    personList() {
      return this.$store.state.personList;
    },
    sum() {
      return this.$store.state.sum;
    },
    // ...mapState(['personList']),
  },
  data() {
    return {
      name: "",
    };
  },
  methods: {
    add() {
      const personObj = { id: nanoid(), name: this.name };
      console.log(personObj);
      this.$store.commit("ADD_PERSON", personObj);
      this.name = "";
    },
  },
};
</script>

<style scoped></style>

// React/shang_react/redux_test/8_react-redux开发者工具的使用/containers/Person/index.jsx
import React, { Component } from "react";
import { nanoid } from "nanoid";
import { connect } from "react-redux";
import { createAddPersonAction } from "../../redux/actions/person";
class Person extends Component {
  addPerson = () => {
    const name = this.nameNode.value;
    const age = this.ageNode.value*1;
    const personObj = { id: nanoid(), name, age };
    // console.log(personObj);
    this.props.jiaYiRen(personObj);
    this.nameNode.value = "";
    this.ageNode.value = "";
  };
  render() {
    return (
      <div>
        <h2>我是Person组件,上方求和为:{this.props.he}</h2>
        <input
          type="text"
          placeholder="请输入你的姓名"
          ref={(c) => (this.nameNode = c)}
        />
        <input
          type="text"
          placeholder="请输入你的年龄"
          ref={(c) => (this.ageNode = c)}
        />
        <button onClick={this.addPerson}>添加</button>
        <ul>
          {this.props.yiduiren.map((p) => {
            return (
              <li key={p.id}>
                {p.name}---{p.age}
              </li>
            );
          })}
        </ul>
      </div>
    );
  }
}
export default connect(
  (state) => ({ yiduiren: state.ren,he:state.he }), //映射状态
  { jiaYiRen: createAddPersonAction } //映射操作状态的方法
)(Person);
